// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/hduhelp/api_open_sdk/schedule/schedule.proto

package schedule

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	baseStaff "github.com/hduhelp/api_open_sdk/baseStaff"
	schoolTime "github.com/hduhelp/api_open_sdk/schoolTime"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ScheduleRequest struct {
	Staff                *baseStaff.Staff `protobuf:"bytes,1,opt,name=Staff,proto3" json:"Staff,omitempty"`
	Semester             int32            `protobuf:"varint,2,opt,name=Semester,proto3" json:"Semester,omitempty"`
	SchoolYear           int32            `protobuf:"varint,3,opt,name=SchoolYear,proto3" json:"SchoolYear,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ScheduleRequest) Reset()         { *m = ScheduleRequest{} }
func (m *ScheduleRequest) String() string { return proto.CompactTextString(m) }
func (*ScheduleRequest) ProtoMessage()    {}
func (*ScheduleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6872b7e52178c395, []int{0}
}

func (m *ScheduleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScheduleRequest.Unmarshal(m, b)
}
func (m *ScheduleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScheduleRequest.Marshal(b, m, deterministic)
}
func (m *ScheduleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduleRequest.Merge(m, src)
}
func (m *ScheduleRequest) XXX_Size() int {
	return xxx_messageInfo_ScheduleRequest.Size(m)
}
func (m *ScheduleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduleRequest proto.InternalMessageInfo

func (m *ScheduleRequest) GetStaff() *baseStaff.Staff {
	if m != nil {
		return m.Staff
	}
	return nil
}

func (m *ScheduleRequest) GetSemester() int32 {
	if m != nil {
		return m.Semester
	}
	return 0
}

func (m *ScheduleRequest) GetSchoolYear() int32 {
	if m != nil {
		return m.SchoolYear
	}
	return 0
}

type Schedule struct {
	Items                map[string]*ScheduleItem `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Schedule) Reset()         { *m = Schedule{} }
func (m *Schedule) String() string { return proto.CompactTextString(m) }
func (*Schedule) ProtoMessage()    {}
func (*Schedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_6872b7e52178c395, []int{1}
}

func (m *Schedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schedule.Unmarshal(m, b)
}
func (m *Schedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schedule.Marshal(b, m, deterministic)
}
func (m *Schedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schedule.Merge(m, src)
}
func (m *Schedule) XXX_Size() int {
	return xxx_messageInfo_Schedule.Size(m)
}
func (m *Schedule) XXX_DiscardUnknown() {
	xxx_messageInfo_Schedule.DiscardUnknown(m)
}

var xxx_messageInfo_Schedule proto.InternalMessageInfo

func (m *Schedule) GetItems() map[string]*ScheduleItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type ScheduleItem struct {
	ClassID              string                 `protobuf:"bytes,1,opt,name=ClassID,proto3" json:"ClassID,omitempty"`
	ClassName            string                 `protobuf:"bytes,2,opt,name=ClassName,proto3" json:"ClassName,omitempty"`
	CourseID             string                 `protobuf:"bytes,3,opt,name=CourseID,proto3" json:"CourseID,omitempty"`
	CourseName           string                 `protobuf:"bytes,4,opt,name=CourseName,proto3" json:"CourseName,omitempty"`
	ClassTime            string                 `protobuf:"bytes,5,opt,name=ClassTime,proto3" json:"ClassTime,omitempty"`
	Credit               string                 `protobuf:"bytes,6,opt,name=Credit,proto3" json:"Credit,omitempty"`
	SchoolYear           *schoolTime.SchoolYear `protobuf:"bytes,7,opt,name=SchoolYear,proto3" json:"SchoolYear,omitempty"`
	Semester             *schoolTime.Semester   `protobuf:"bytes,8,opt,name=Semester,proto3" json:"Semester,omitempty"`
	SeatsNum             int32                  `protobuf:"varint,9,opt,name=SeatsNum,proto3" json:"SeatsNum,omitempty"`
	Commit               string                 `protobuf:"bytes,10,opt,name=Commit,proto3" json:"Commit,omitempty"`
	Week                 []int32                `protobuf:"varint,11,rep,packed,name=Week,proto3" json:"Week,omitempty"`
	WeekDay              int32                  `protobuf:"varint,12,opt,name=WeekDay,proto3" json:"WeekDay,omitempty"`
	Teachers             *baseStaff.InfoMapList `protobuf:"bytes,13,opt,name=Teachers,proto3" json:"Teachers,omitempty"`
	Students             *baseStaff.InfoMapList `protobuf:"bytes,14,opt,name=Students,proto3" json:"Students,omitempty"`
	Section              []int32                `protobuf:"varint,15,rep,packed,name=Section,proto3" json:"Section,omitempty"`
	StartTime            int64                  `protobuf:"varint,16,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime              int64                  `protobuf:"varint,17,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	Location             string                 `protobuf:"bytes,18,opt,name=Location,proto3" json:"Location,omitempty"`
	IsThisWeek           bool                   `protobuf:"varint,19,opt,name=IsThisWeek,proto3" json:"IsThisWeek,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ScheduleItem) Reset()         { *m = ScheduleItem{} }
func (m *ScheduleItem) String() string { return proto.CompactTextString(m) }
func (*ScheduleItem) ProtoMessage()    {}
func (*ScheduleItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_6872b7e52178c395, []int{2}
}

func (m *ScheduleItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScheduleItem.Unmarshal(m, b)
}
func (m *ScheduleItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScheduleItem.Marshal(b, m, deterministic)
}
func (m *ScheduleItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduleItem.Merge(m, src)
}
func (m *ScheduleItem) XXX_Size() int {
	return xxx_messageInfo_ScheduleItem.Size(m)
}
func (m *ScheduleItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduleItem.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduleItem proto.InternalMessageInfo

func (m *ScheduleItem) GetClassID() string {
	if m != nil {
		return m.ClassID
	}
	return ""
}

func (m *ScheduleItem) GetClassName() string {
	if m != nil {
		return m.ClassName
	}
	return ""
}

func (m *ScheduleItem) GetCourseID() string {
	if m != nil {
		return m.CourseID
	}
	return ""
}

func (m *ScheduleItem) GetCourseName() string {
	if m != nil {
		return m.CourseName
	}
	return ""
}

func (m *ScheduleItem) GetClassTime() string {
	if m != nil {
		return m.ClassTime
	}
	return ""
}

func (m *ScheduleItem) GetCredit() string {
	if m != nil {
		return m.Credit
	}
	return ""
}

func (m *ScheduleItem) GetSchoolYear() *schoolTime.SchoolYear {
	if m != nil {
		return m.SchoolYear
	}
	return nil
}

func (m *ScheduleItem) GetSemester() *schoolTime.Semester {
	if m != nil {
		return m.Semester
	}
	return nil
}

func (m *ScheduleItem) GetSeatsNum() int32 {
	if m != nil {
		return m.SeatsNum
	}
	return 0
}

func (m *ScheduleItem) GetCommit() string {
	if m != nil {
		return m.Commit
	}
	return ""
}

func (m *ScheduleItem) GetWeek() []int32 {
	if m != nil {
		return m.Week
	}
	return nil
}

func (m *ScheduleItem) GetWeekDay() int32 {
	if m != nil {
		return m.WeekDay
	}
	return 0
}

func (m *ScheduleItem) GetTeachers() *baseStaff.InfoMapList {
	if m != nil {
		return m.Teachers
	}
	return nil
}

func (m *ScheduleItem) GetStudents() *baseStaff.InfoMapList {
	if m != nil {
		return m.Students
	}
	return nil
}

func (m *ScheduleItem) GetSection() []int32 {
	if m != nil {
		return m.Section
	}
	return nil
}

func (m *ScheduleItem) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *ScheduleItem) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *ScheduleItem) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *ScheduleItem) GetIsThisWeek() bool {
	if m != nil {
		return m.IsThisWeek
	}
	return false
}

type StaffInfo struct {
	StaffID              string   `protobuf:"bytes,1,opt,name=StaffID,proto3" json:"StaffID,omitempty"`
	StaffName            string   `protobuf:"bytes,2,opt,name=StaffName,proto3" json:"StaffName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaffInfo) Reset()         { *m = StaffInfo{} }
func (m *StaffInfo) String() string { return proto.CompactTextString(m) }
func (*StaffInfo) ProtoMessage()    {}
func (*StaffInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6872b7e52178c395, []int{3}
}

func (m *StaffInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaffInfo.Unmarshal(m, b)
}
func (m *StaffInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaffInfo.Marshal(b, m, deterministic)
}
func (m *StaffInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaffInfo.Merge(m, src)
}
func (m *StaffInfo) XXX_Size() int {
	return xxx_messageInfo_StaffInfo.Size(m)
}
func (m *StaffInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StaffInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StaffInfo proto.InternalMessageInfo

func (m *StaffInfo) GetStaffID() string {
	if m != nil {
		return m.StaffID
	}
	return ""
}

func (m *StaffInfo) GetStaffName() string {
	if m != nil {
		return m.StaffName
	}
	return ""
}

func init() {
	proto.RegisterType((*ScheduleRequest)(nil), "schedule.ScheduleRequest")
	proto.RegisterType((*Schedule)(nil), "schedule.Schedule")
	proto.RegisterMapType((map[string]*ScheduleItem)(nil), "schedule.Schedule.ItemsEntry")
	proto.RegisterType((*ScheduleItem)(nil), "schedule.ScheduleItem")
	proto.RegisterType((*StaffInfo)(nil), "schedule.StaffInfo")
}

func init() {
	proto.RegisterFile("github.com/hduhelp/api_open_sdk/schedule/schedule.proto", fileDescriptor_6872b7e52178c395)
}

var fileDescriptor_6872b7e52178c395 = []byte{
	// 581 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0xfd, 0xb9, 0xa9, 0x5b, 0x7b, 0xd3, 0x1f, 0x2d, 0x0b, 0x2a, 0x4b, 0x04, 0xc8, 0xca, 0x01,
	0xf9, 0x80, 0x12, 0x94, 0x4a, 0xfc, 0x3d, 0x26, 0x15, 0x04, 0x95, 0x0a, 0xad, 0x23, 0x55, 0x9c,
	0xaa, 0x4d, 0x3c, 0xc6, 0x56, 0x62, 0x3b, 0x78, 0xd7, 0x48, 0xf9, 0x18, 0x7c, 0x5d, 0x4e, 0x68,
	0xc7, 0x5e, 0xdb, 0x55, 0x24, 0xe0, 0xd2, 0xce, 0x9b, 0xb7, 0x33, 0xf3, 0x76, 0xde, 0x3a, 0xe4,
	0xf5, 0xb7, 0x44, 0xc5, 0xe5, 0x72, 0xb4, 0xca, 0xd3, 0x71, 0x1c, 0x96, 0x31, 0x6c, 0xb6, 0x63,
	0xb1, 0x4d, 0x6e, 0xf3, 0x2d, 0x64, 0xb7, 0x32, 0x5c, 0x8f, 0xe5, 0x2a, 0x86, 0xb0, 0xdc, 0x40,
	0x13, 0x8c, 0xb6, 0x45, 0xae, 0x72, 0xea, 0x18, 0x3c, 0x78, 0xfb, 0xb7, 0x16, 0x4b, 0x21, 0x21,
	0x50, 0x22, 0x8a, 0xda, 0xa8, 0x6a, 0x32, 0x78, 0xff, 0x0f, 0xd3, 0xf3, 0x7c, 0xb3, 0x48, 0x52,
	0xe8, 0x84, 0x55, 0xf1, 0xb0, 0x24, 0xa7, 0x41, 0xad, 0x81, 0xc3, 0xf7, 0x12, 0xa4, 0xa2, 0xcf,
	0x89, 0x8d, 0xed, 0x99, 0xe5, 0x59, 0x7e, 0x7f, 0x72, 0x36, 0x6a, 0x07, 0xe2, 0x5f, 0x5e, 0xd1,
	0x74, 0x40, 0x9c, 0x00, 0x52, 0x90, 0x0a, 0x0a, 0x76, 0xe0, 0x59, 0xbe, 0xcd, 0x1b, 0x4c, 0x9f,
	0x11, 0x12, 0xe0, 0xa8, 0xaf, 0x20, 0x0a, 0xd6, 0x43, 0xb6, 0x93, 0x19, 0xfe, 0xb4, 0x88, 0x63,
	0xe6, 0xd2, 0x0b, 0x62, 0xcf, 0x15, 0xa4, 0x92, 0x59, 0x5e, 0xcf, 0xef, 0x4f, 0x9e, 0x8e, 0x9a,
	0x2d, 0x99, 0x23, 0x23, 0xe4, 0x2f, 0x33, 0x55, 0xec, 0x78, 0x75, 0x76, 0xf0, 0x85, 0x90, 0x36,
	0x49, 0xcf, 0x48, 0x6f, 0x0d, 0x3b, 0x54, 0xec, 0x72, 0x1d, 0xd2, 0x17, 0xc4, 0xfe, 0x21, 0x36,
	0x25, 0xa0, 0xb4, 0xfe, 0xe4, 0x7c, 0xbf, 0xa9, 0x2e, 0xe7, 0xd5, 0xa1, 0x77, 0x07, 0x6f, 0xac,
	0xe1, 0xaf, 0x43, 0x72, 0xd2, 0xe5, 0x28, 0x23, 0xc7, 0xd3, 0x8d, 0x90, 0x72, 0x3e, 0xab, 0x1b,
	0x1b, 0x48, 0x9f, 0x10, 0x17, 0xc3, 0x6b, 0x91, 0x56, 0x03, 0x5c, 0xde, 0x26, 0xf4, 0x62, 0xa6,
	0x79, 0x59, 0x48, 0x98, 0xcf, 0xf0, 0xea, 0x2e, 0x6f, 0xb0, 0x5e, 0x4c, 0x15, 0x63, 0xe9, 0x21,
	0xb2, 0x9d, 0x4c, 0xd3, 0x59, 0x5b, 0xc4, 0xec, 0x4e, 0x67, 0x9d, 0xa0, 0xe7, 0xe4, 0x68, 0x5a,
	0x40, 0x98, 0x28, 0x76, 0x84, 0x54, 0x8d, 0xe8, 0xab, 0x3b, 0xeb, 0x3e, 0x6e, 0x6f, 0x6c, 0xcc,
	0x6e, 0xd9, 0xae, 0x0d, 0xf4, 0x65, 0xc7, 0x42, 0x07, 0xab, 0x1e, 0xde, 0xa9, 0xaa, 0xb9, 0x8e,
	0xb1, 0x68, 0xba, 0x50, 0xf2, 0xba, 0x4c, 0x99, 0x6b, 0x4c, 0xaf, 0x30, 0xaa, 0xcb, 0xd3, 0x34,
	0x51, 0x8c, 0xd4, 0xea, 0x10, 0x51, 0x4a, 0x0e, 0x6f, 0x00, 0xd6, 0xac, 0xef, 0xf5, 0x7c, 0x9b,
	0x63, 0xac, 0x77, 0xab, 0xff, 0xcf, 0xc4, 0x8e, 0x9d, 0x60, 0x1b, 0x03, 0xe9, 0x84, 0x38, 0x0b,
	0x10, 0xab, 0x18, 0x0a, 0xc9, 0xfe, 0xaf, 0x6f, 0xd2, 0xbe, 0xc0, 0x79, 0x16, 0xe5, 0x9f, 0xc5,
	0xf6, 0x2a, 0x91, 0x8a, 0x37, 0xe7, 0x74, 0x4d, 0xa0, 0xca, 0x10, 0x32, 0x25, 0xd9, 0xbd, 0x3f,
	0xd7, 0x98, 0x73, 0x5a, 0x41, 0x00, 0x2b, 0x95, 0xe4, 0x19, 0x3b, 0x45, 0x61, 0x06, 0x6a, 0x0f,
	0x02, 0x25, 0x0a, 0x85, 0x1e, 0x9c, 0x79, 0x96, 0xdf, 0xe3, 0x6d, 0x42, 0xd7, 0x5d, 0x66, 0x21,
	0x72, 0xf7, 0x91, 0x33, 0x50, 0xef, 0xe6, 0x2a, 0x5f, 0x09, 0x6c, 0x49, 0x2b, 0xdf, 0x0d, 0xd6,
	0xbe, 0xcf, 0xe5, 0x22, 0x4e, 0x24, 0x6e, 0xe2, 0x81, 0x67, 0xf9, 0x0e, 0xef, 0x64, 0x86, 0x53,
	0x9c, 0x19, 0x45, 0x5a, 0x2b, 0x4a, 0x43, 0xd0, 0x3c, 0xbc, 0x1a, 0xd6, 0xd2, 0xa2, 0xa8, 0xfb,
	0xf0, 0x9a, 0xc4, 0xe4, 0x86, 0xb8, 0xe6, 0x01, 0x17, 0xf4, 0x13, 0x79, 0x84, 0xcc, 0x07, 0x50,
	0x26, 0xf9, 0x51, 0x64, 0xa1, 0xa6, 0x1e, 0xef, 0x7f, 0x0c, 0xf5, 0xc7, 0x3f, 0xa0, 0xfb, 0xd4,
	0xf0, 0xbf, 0xe5, 0x11, 0xfe, 0x58, 0x5c, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x6a, 0xf7, 0x6b,
	0x1f, 0xe9, 0x04, 0x00, 0x00,
}
