// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package schedule

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ScheduleServerClient is the client API for ScheduleServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScheduleServerClient interface {
	StaffGetScheduleHandler(ctx context.Context, in *ScheduleRequest, opts ...grpc.CallOption) (*Schedule, error)
}

type scheduleServerClient struct {
	cc grpc.ClientConnInterface
}

func NewScheduleServerClient(cc grpc.ClientConnInterface) ScheduleServerClient {
	return &scheduleServerClient{cc}
}

func (c *scheduleServerClient) StaffGetScheduleHandler(ctx context.Context, in *ScheduleRequest, opts ...grpc.CallOption) (*Schedule, error) {
	out := new(Schedule)
	err := c.cc.Invoke(ctx, "/schedule.ScheduleServer/StaffGetScheduleHandler", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScheduleServerServer is the server API for ScheduleServer service.
// All implementations must embed UnimplementedScheduleServerServer
// for forward compatibility
type ScheduleServerServer interface {
	StaffGetScheduleHandler(context.Context, *ScheduleRequest) (*Schedule, error)
	mustEmbedUnimplementedScheduleServerServer()
}

// UnimplementedScheduleServerServer must be embedded to have forward compatible implementations.
type UnimplementedScheduleServerServer struct {
}

func (UnimplementedScheduleServerServer) StaffGetScheduleHandler(context.Context, *ScheduleRequest) (*Schedule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffGetScheduleHandler not implemented")
}
func (UnimplementedScheduleServerServer) mustEmbedUnimplementedScheduleServerServer() {}

// UnsafeScheduleServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScheduleServerServer will
// result in compilation errors.
type UnsafeScheduleServerServer interface {
	mustEmbedUnimplementedScheduleServerServer()
}

func RegisterScheduleServerServer(s grpc.ServiceRegistrar, srv ScheduleServerServer) {
	s.RegisterService(&ScheduleServer_ServiceDesc, srv)
}

func _ScheduleServer_StaffGetScheduleHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServerServer).StaffGetScheduleHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schedule.ScheduleServer/StaffGetScheduleHandler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServerServer).StaffGetScheduleHandler(ctx, req.(*ScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScheduleServer_ServiceDesc is the grpc.ServiceDesc for ScheduleServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScheduleServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "schedule.ScheduleServer",
	HandlerType: (*ScheduleServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StaffGetScheduleHandler",
			Handler:    _ScheduleServer_StaffGetScheduleHandler_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/hduhelp/api_open_sdk/schedule/schedule.proto",
}
