// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/hduhelp/api_open_sdk/baseStaff/baseStaff.proto

package baseStaff

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Type int32

const (
	Type_Undergraduate Type = 0
	Type_Teacher       Type = 1
	Type_Postgraduate  Type = 2
)

var Type_name = map[int32]string{
	0: "Undergraduate",
	1: "Teacher",
	2: "Postgraduate",
}

var Type_value = map[string]int32{
	"Undergraduate": 0,
	"Teacher":       1,
	"Postgraduate":  2,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0001ec504db3213, []int{0}
}

type Staff struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Type                 Type     `protobuf:"varint,2,opt,name=Type,proto3,enum=baseStaff.Type" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Staff) Reset()         { *m = Staff{} }
func (m *Staff) String() string { return proto.CompactTextString(m) }
func (*Staff) ProtoMessage()    {}
func (*Staff) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0001ec504db3213, []int{0}
}

func (m *Staff) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Staff.Unmarshal(m, b)
}
func (m *Staff) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Staff.Marshal(b, m, deterministic)
}
func (m *Staff) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Staff.Merge(m, src)
}
func (m *Staff) XXX_Size() int {
	return xxx_messageInfo_Staff.Size(m)
}
func (m *Staff) XXX_DiscardUnknown() {
	xxx_messageInfo_Staff.DiscardUnknown(m)
}

var xxx_messageInfo_Staff proto.InternalMessageInfo

func (m *Staff) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Staff) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_Undergraduate
}

type Info struct {
	StaffID              string   `protobuf:"bytes,1,opt,name=StaffID,proto3" json:"StaffID,omitempty"`
	StaffName            string   `protobuf:"bytes,2,opt,name=StaffName,proto3" json:"StaffName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0001ec504db3213, []int{1}
}

func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (m *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(m, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetStaffID() string {
	if m != nil {
		return m.StaffID
	}
	return ""
}

func (m *Info) GetStaffName() string {
	if m != nil {
		return m.StaffName
	}
	return ""
}

type InfoMapList struct {
	Items                map[string]*Info `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *InfoMapList) Reset()         { *m = InfoMapList{} }
func (m *InfoMapList) String() string { return proto.CompactTextString(m) }
func (*InfoMapList) ProtoMessage()    {}
func (*InfoMapList) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0001ec504db3213, []int{2}
}

func (m *InfoMapList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoMapList.Unmarshal(m, b)
}
func (m *InfoMapList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoMapList.Marshal(b, m, deterministic)
}
func (m *InfoMapList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoMapList.Merge(m, src)
}
func (m *InfoMapList) XXX_Size() int {
	return xxx_messageInfo_InfoMapList.Size(m)
}
func (m *InfoMapList) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoMapList.DiscardUnknown(m)
}

var xxx_messageInfo_InfoMapList proto.InternalMessageInfo

func (m *InfoMapList) GetItems() map[string]*Info {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterEnum("baseStaff.Type", Type_name, Type_value)
	proto.RegisterType((*Staff)(nil), "baseStaff.Staff")
	proto.RegisterType((*Info)(nil), "baseStaff.Info")
	proto.RegisterType((*InfoMapList)(nil), "baseStaff.InfoMapList")
	proto.RegisterMapType((map[string]*Info)(nil), "baseStaff.InfoMapList.ItemsEntry")
}

func init() {
	proto.RegisterFile("github.com/hduhelp/api_open_sdk/baseStaff/baseStaff.proto", fileDescriptor_a0001ec504db3213)
}

var fileDescriptor_a0001ec504db3213 = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4f, 0xbb, 0x40,
	0x10, 0xc5, 0xff, 0x4b, 0xdb, 0x7f, 0xc3, 0xa0, 0x15, 0xe7, 0x44, 0x8c, 0x07, 0xc4, 0x98, 0x10,
	0x0f, 0x90, 0xd4, 0x83, 0xd5, 0x18, 0x4f, 0xf5, 0x40, 0xa2, 0xc6, 0x60, 0x3d, 0x37, 0x4b, 0x59,
	0x0a, 0x69, 0x61, 0x37, 0xb0, 0x98, 0xf0, 0x31, 0xfc, 0xc6, 0x86, 0x45, 0xa1, 0xde, 0xde, 0xbe,
	0xf7, 0xf2, 0xdb, 0x99, 0x81, 0xbb, 0x6d, 0x26, 0xd3, 0x3a, 0xf2, 0x36, 0x3c, 0xf7, 0xd3, 0xb8,
	0x4e, 0xd9, 0x5e, 0xf8, 0x54, 0x64, 0x6b, 0x2e, 0x58, 0xb1, 0xae, 0xe2, 0x9d, 0x1f, 0xd1, 0x8a,
	0xbd, 0x4b, 0x9a, 0x24, 0x83, 0xf2, 0x44, 0xc9, 0x25, 0x47, 0xbd, 0x37, 0x9c, 0x07, 0x98, 0x28,
	0x81, 0x33, 0xd0, 0x82, 0xa5, 0x45, 0x6c, 0xe2, 0xea, 0xa1, 0x16, 0x2c, 0xf1, 0x12, 0xc6, 0xab,
	0x46, 0x30, 0x4b, 0xb3, 0x89, 0x3b, 0x9b, 0x9f, 0x78, 0x03, 0xa3, 0xb5, 0x43, 0x15, 0x3a, 0x8f,
	0x30, 0x0e, 0x8a, 0x84, 0xa3, 0x05, 0x53, 0x95, 0xf5, 0x84, 0xdf, 0x27, 0x9e, 0x83, 0xae, 0xe4,
	0x2b, 0xcd, 0x3b, 0x96, 0x1e, 0x0e, 0x86, 0xf3, 0x45, 0xc0, 0x68, 0x01, 0x2f, 0x54, 0x3c, 0x67,
	0x95, 0xc4, 0x5b, 0x98, 0x04, 0x92, 0xe5, 0x95, 0x45, 0xec, 0x91, 0x6b, 0xcc, 0x2f, 0x0e, 0x7e,
	0x3d, 0xa8, 0x79, 0xaa, 0xf3, 0x54, 0xc8, 0xb2, 0x09, 0xbb, 0xfe, 0x59, 0x00, 0x30, 0x98, 0x68,
	0xc2, 0x68, 0xc7, 0x9a, 0x9f, 0x51, 0x5a, 0x89, 0x57, 0x30, 0xf9, 0xa4, 0xfb, 0xba, 0x1b, 0xc1,
	0xf8, 0xb3, 0x4e, 0x0b, 0x0e, 0xbb, 0xf4, 0x5e, 0x5b, 0x90, 0xeb, 0x45, 0xb7, 0x38, 0x9e, 0xc2,
	0xf1, 0x47, 0x11, 0xb3, 0x72, 0x5b, 0xd2, 0xb8, 0xa6, 0x92, 0x99, 0xff, 0xd0, 0x80, 0xe9, 0x8a,
	0xd1, 0x4d, 0xca, 0x4a, 0x93, 0xa0, 0x09, 0x47, 0x6f, 0xbc, 0x92, 0x7d, 0xac, 0x45, 0xff, 0xd5,
	0x75, 0x6f, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x37, 0xef, 0x8a, 0x19, 0x9a, 0x01, 0x00, 0x00,
}
