// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: campusapis/third/v1/weixiao.proto

package thirdv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WeixiaoService_GetSchoolCardBalance_FullMethodName  = "/campusapis.third.v1.WeixiaoService/GetSchoolCardBalance"
	WeixiaoService_GetLibraryBorrow_FullMethodName      = "/campusapis.third.v1.WeixiaoService/GetLibraryBorrow"
	WeixiaoService_GetStudentCourse_FullMethodName      = "/campusapis.third.v1.WeixiaoService/GetStudentCourse"
	WeixiaoService_GetStudentCourseScore_FullMethodName = "/campusapis.third.v1.WeixiaoService/GetStudentCourseScore"
	WeixiaoService_GetStudentExam_FullMethodName        = "/campusapis.third.v1.WeixiaoService/GetStudentExam"
)

// WeixiaoServiceClient is the client API for WeixiaoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 微校卡数据同步接口
type WeixiaoServiceClient interface {
	// 用户校园卡面余额字段同步
	// https://wiki.weixiao.qq.com/api/school/balance.html
	GetSchoolCardBalance(ctx context.Context, in *CommonWeixiaoPostRequest, opts ...grpc.CallOption) (*CommonWeixiaoPostResponse, error)
	// 用户校园卡面借书字段同步
	// https://wiki.weixiao.qq.com/api/school/borrow.html
	GetLibraryBorrow(ctx context.Context, in *CommonWeixiaoPostRequest, opts ...grpc.CallOption) (*CommonWeixiaoPostResponse, error)
	// 查课表Pro数据同步
	// https://wiki.weixiao.qq.com/api/school/course.html
	GetStudentCourse(ctx context.Context, in *CommonWeixiaoPostRequest, opts ...grpc.CallOption) (*CommonWeixiaoPostResponse, error)
	// 查成绩Pro数据同步
	// https://wiki.weixiao.qq.com/api/school/courseScore.html
	GetStudentCourseScore(ctx context.Context, in *CommonWeixiaoPostRequest, opts ...grpc.CallOption) (*CommonWeixiaoPostResponse, error)
	// 查考试数据同步
	// https://wiki.weixiao.qq.com/api/school/checkExam.html
	GetStudentExam(ctx context.Context, in *CommonWeixiaoPostRequest, opts ...grpc.CallOption) (*CommonWeixiaoPostResponse, error)
}

type weixiaoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWeixiaoServiceClient(cc grpc.ClientConnInterface) WeixiaoServiceClient {
	return &weixiaoServiceClient{cc}
}

func (c *weixiaoServiceClient) GetSchoolCardBalance(ctx context.Context, in *CommonWeixiaoPostRequest, opts ...grpc.CallOption) (*CommonWeixiaoPostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonWeixiaoPostResponse)
	err := c.cc.Invoke(ctx, WeixiaoService_GetSchoolCardBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weixiaoServiceClient) GetLibraryBorrow(ctx context.Context, in *CommonWeixiaoPostRequest, opts ...grpc.CallOption) (*CommonWeixiaoPostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonWeixiaoPostResponse)
	err := c.cc.Invoke(ctx, WeixiaoService_GetLibraryBorrow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weixiaoServiceClient) GetStudentCourse(ctx context.Context, in *CommonWeixiaoPostRequest, opts ...grpc.CallOption) (*CommonWeixiaoPostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonWeixiaoPostResponse)
	err := c.cc.Invoke(ctx, WeixiaoService_GetStudentCourse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weixiaoServiceClient) GetStudentCourseScore(ctx context.Context, in *CommonWeixiaoPostRequest, opts ...grpc.CallOption) (*CommonWeixiaoPostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonWeixiaoPostResponse)
	err := c.cc.Invoke(ctx, WeixiaoService_GetStudentCourseScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weixiaoServiceClient) GetStudentExam(ctx context.Context, in *CommonWeixiaoPostRequest, opts ...grpc.CallOption) (*CommonWeixiaoPostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonWeixiaoPostResponse)
	err := c.cc.Invoke(ctx, WeixiaoService_GetStudentExam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeixiaoServiceServer is the server API for WeixiaoService service.
// All implementations must embed UnimplementedWeixiaoServiceServer
// for forward compatibility.
//
// 微校卡数据同步接口
type WeixiaoServiceServer interface {
	// 用户校园卡面余额字段同步
	// https://wiki.weixiao.qq.com/api/school/balance.html
	GetSchoolCardBalance(context.Context, *CommonWeixiaoPostRequest) (*CommonWeixiaoPostResponse, error)
	// 用户校园卡面借书字段同步
	// https://wiki.weixiao.qq.com/api/school/borrow.html
	GetLibraryBorrow(context.Context, *CommonWeixiaoPostRequest) (*CommonWeixiaoPostResponse, error)
	// 查课表Pro数据同步
	// https://wiki.weixiao.qq.com/api/school/course.html
	GetStudentCourse(context.Context, *CommonWeixiaoPostRequest) (*CommonWeixiaoPostResponse, error)
	// 查成绩Pro数据同步
	// https://wiki.weixiao.qq.com/api/school/courseScore.html
	GetStudentCourseScore(context.Context, *CommonWeixiaoPostRequest) (*CommonWeixiaoPostResponse, error)
	// 查考试数据同步
	// https://wiki.weixiao.qq.com/api/school/checkExam.html
	GetStudentExam(context.Context, *CommonWeixiaoPostRequest) (*CommonWeixiaoPostResponse, error)
	mustEmbedUnimplementedWeixiaoServiceServer()
}

// UnimplementedWeixiaoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWeixiaoServiceServer struct{}

func (UnimplementedWeixiaoServiceServer) GetSchoolCardBalance(context.Context, *CommonWeixiaoPostRequest) (*CommonWeixiaoPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSchoolCardBalance not implemented")
}
func (UnimplementedWeixiaoServiceServer) GetLibraryBorrow(context.Context, *CommonWeixiaoPostRequest) (*CommonWeixiaoPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLibraryBorrow not implemented")
}
func (UnimplementedWeixiaoServiceServer) GetStudentCourse(context.Context, *CommonWeixiaoPostRequest) (*CommonWeixiaoPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudentCourse not implemented")
}
func (UnimplementedWeixiaoServiceServer) GetStudentCourseScore(context.Context, *CommonWeixiaoPostRequest) (*CommonWeixiaoPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudentCourseScore not implemented")
}
func (UnimplementedWeixiaoServiceServer) GetStudentExam(context.Context, *CommonWeixiaoPostRequest) (*CommonWeixiaoPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudentExam not implemented")
}
func (UnimplementedWeixiaoServiceServer) mustEmbedUnimplementedWeixiaoServiceServer() {}
func (UnimplementedWeixiaoServiceServer) testEmbeddedByValue()                        {}

// UnsafeWeixiaoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeixiaoServiceServer will
// result in compilation errors.
type UnsafeWeixiaoServiceServer interface {
	mustEmbedUnimplementedWeixiaoServiceServer()
}

func RegisterWeixiaoServiceServer(s grpc.ServiceRegistrar, srv WeixiaoServiceServer) {
	// If the following call pancis, it indicates UnimplementedWeixiaoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WeixiaoService_ServiceDesc, srv)
}

func _WeixiaoService_GetSchoolCardBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonWeixiaoPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeixiaoServiceServer).GetSchoolCardBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeixiaoService_GetSchoolCardBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeixiaoServiceServer).GetSchoolCardBalance(ctx, req.(*CommonWeixiaoPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeixiaoService_GetLibraryBorrow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonWeixiaoPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeixiaoServiceServer).GetLibraryBorrow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeixiaoService_GetLibraryBorrow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeixiaoServiceServer).GetLibraryBorrow(ctx, req.(*CommonWeixiaoPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeixiaoService_GetStudentCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonWeixiaoPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeixiaoServiceServer).GetStudentCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeixiaoService_GetStudentCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeixiaoServiceServer).GetStudentCourse(ctx, req.(*CommonWeixiaoPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeixiaoService_GetStudentCourseScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonWeixiaoPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeixiaoServiceServer).GetStudentCourseScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeixiaoService_GetStudentCourseScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeixiaoServiceServer).GetStudentCourseScore(ctx, req.(*CommonWeixiaoPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeixiaoService_GetStudentExam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonWeixiaoPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeixiaoServiceServer).GetStudentExam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeixiaoService_GetStudentExam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeixiaoServiceServer).GetStudentExam(ctx, req.(*CommonWeixiaoPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WeixiaoService_ServiceDesc is the grpc.ServiceDesc for WeixiaoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WeixiaoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "campusapis.third.v1.WeixiaoService",
	HandlerType: (*WeixiaoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSchoolCardBalance",
			Handler:    _WeixiaoService_GetSchoolCardBalance_Handler,
		},
		{
			MethodName: "GetLibraryBorrow",
			Handler:    _WeixiaoService_GetLibraryBorrow_Handler,
		},
		{
			MethodName: "GetStudentCourse",
			Handler:    _WeixiaoService_GetStudentCourse_Handler,
		},
		{
			MethodName: "GetStudentCourseScore",
			Handler:    _WeixiaoService_GetStudentCourseScore_Handler,
		},
		{
			MethodName: "GetStudentExam",
			Handler:    _WeixiaoService_GetStudentExam_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "campusapis/third/v1/weixiao.proto",
}
