// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package student

import (
	context "context"
	baseStaff "github.com/hduhelp/api_open_sdk/baseStaff"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StudentServerClient is the client API for StudentServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StudentServerClient interface {
	BirthdayHandler(ctx context.Context, in *baseStaff.Staff, opts ...grpc.CallOption) (*BirthdayResponse, error)
	BirthdaysHandler(ctx context.Context, in *BirthdaysRequest, opts ...grpc.CallOption) (*BirthdaysResponse, error)
	GateAccessHandler(ctx context.Context, in *GateAccessRequest, opts ...grpc.CallOption) (*GateAccessResponse, error)
}

type studentServerClient struct {
	cc grpc.ClientConnInterface
}

func NewStudentServerClient(cc grpc.ClientConnInterface) StudentServerClient {
	return &studentServerClient{cc}
}

func (c *studentServerClient) BirthdayHandler(ctx context.Context, in *baseStaff.Staff, opts ...grpc.CallOption) (*BirthdayResponse, error) {
	out := new(BirthdayResponse)
	err := c.cc.Invoke(ctx, "/student.StudentServer/BirthdayHandler", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentServerClient) BirthdaysHandler(ctx context.Context, in *BirthdaysRequest, opts ...grpc.CallOption) (*BirthdaysResponse, error) {
	out := new(BirthdaysResponse)
	err := c.cc.Invoke(ctx, "/student.StudentServer/BirthdaysHandler", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentServerClient) GateAccessHandler(ctx context.Context, in *GateAccessRequest, opts ...grpc.CallOption) (*GateAccessResponse, error) {
	out := new(GateAccessResponse)
	err := c.cc.Invoke(ctx, "/student.StudentServer/GateAccessHandler", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudentServerServer is the server API for StudentServer service.
// All implementations must embed UnimplementedStudentServerServer
// for forward compatibility
type StudentServerServer interface {
	BirthdayHandler(context.Context, *baseStaff.Staff) (*BirthdayResponse, error)
	BirthdaysHandler(context.Context, *BirthdaysRequest) (*BirthdaysResponse, error)
	GateAccessHandler(context.Context, *GateAccessRequest) (*GateAccessResponse, error)
	mustEmbedUnimplementedStudentServerServer()
}

// UnimplementedStudentServerServer must be embedded to have forward compatible implementations.
type UnimplementedStudentServerServer struct {
}

func (UnimplementedStudentServerServer) BirthdayHandler(context.Context, *baseStaff.Staff) (*BirthdayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BirthdayHandler not implemented")
}
func (UnimplementedStudentServerServer) BirthdaysHandler(context.Context, *BirthdaysRequest) (*BirthdaysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BirthdaysHandler not implemented")
}
func (UnimplementedStudentServerServer) GateAccessHandler(context.Context, *GateAccessRequest) (*GateAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GateAccessHandler not implemented")
}
func (UnimplementedStudentServerServer) mustEmbedUnimplementedStudentServerServer() {}

// UnsafeStudentServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StudentServerServer will
// result in compilation errors.
type UnsafeStudentServerServer interface {
	mustEmbedUnimplementedStudentServerServer()
}

func RegisterStudentServerServer(s grpc.ServiceRegistrar, srv StudentServerServer) {
	s.RegisterService(&StudentServer_ServiceDesc, srv)
}

func _StudentServer_BirthdayHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(baseStaff.Staff)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServerServer).BirthdayHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/student.StudentServer/BirthdayHandler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServerServer).BirthdayHandler(ctx, req.(*baseStaff.Staff))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentServer_BirthdaysHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BirthdaysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServerServer).BirthdaysHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/student.StudentServer/BirthdaysHandler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServerServer).BirthdaysHandler(ctx, req.(*BirthdaysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentServer_GateAccessHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GateAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServerServer).GateAccessHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/student.StudentServer/GateAccessHandler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServerServer).GateAccessHandler(ctx, req.(*GateAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StudentServer_ServiceDesc is the grpc.ServiceDesc for StudentServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StudentServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "student.StudentServer",
	HandlerType: (*StudentServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BirthdayHandler",
			Handler:    _StudentServer_BirthdayHandler_Handler,
		},
		{
			MethodName: "BirthdaysHandler",
			Handler:    _StudentServer_BirthdaysHandler_Handler,
		},
		{
			MethodName: "GateAccessHandler",
			Handler:    _StudentServer_GateAccessHandler_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "baseStaff/student/student.proto",
}
