name: check buf generate up to date
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "*.proto"
      - "buf.yaml"
      - ".github/workflows/buf-lint.yaml"

jobs:
  lint-protos:
    # Run `git checkout`
    - uses: actions/checkout@v3
    # Install the `buf` CLI
    - uses: bufbuild/buf-setup-action@v1
    # Lint your Protobuf sources
    - uses: bufbuild/buf-lint-action@v1