name: check buf generate up to date
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: load Go 1.18 env
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
        id: go

      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - uses: actions/cache@v3
        id: cache-golang
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: init dependance
        if: steps.cache-golang.outputs.cache-hit != 'true'
        run: make install-tools

      - name: generate proto
        run: make generate-proto

      - name: check if files up to date
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'FDKevin'
            git config --global user.email 'fdkevinzero@gmail.com'
            git add -A
            git commit -m "ci(gen): buf generate up to date"
            git push
          fi
      
      - name: warming go proxy proxy.golang.org
        uses: andrewslotin/go-proxy-pull-action@master

      - name: warming go proxy goproxy.cn
        uses: andrewslotin/go-proxy-pull-action@master
        with:
          goproxy: https://goproxy.cn